openapi: 3.0.1
info:
  title: Serverless PDF Tools API
  description: Serverless API for building and processing PDF files. Built on AWS Lambda
  version: 0.0.1
tags:
  - name: pdf
    description: PDF operations
  - name: html
    description: HTML operations
security:
  - ApiKey: []
paths:
  /pdf:
    post:
      operationId: composePDF
      summary: Compose a PDF file
      description: |
        Composes a PDF file from recipe and serves it in desired formats
      tags:
        - pdf
      requestBody:
        $ref: '#/components/requestBodies/ComposePdfPayload'
      responses:
        200:
          description: ok
          content: 
            image/png: 
              schema:
                type: string
                format: binary
            application/pdf: 
              schema:
                type: string
                format: binary
  /html:
    post:
      operationId: composeHTML
      summary: Compose a HTML page
      description: |
        Composes a PDF file from recipe and serves it in desired formats
      tags:
        - html
      requestBody:
        $ref: '#/components/requestBodies/ComposeHtmlPayload'
      responses:
        200:
          description: ok
          content: 
            image/png:
              schema:
                type: string
                format: binary
            application/pdf: 
              schema:
                type: string
                format: binary
components:
  securitySchemes:
    ApiKey:
      type: 'apiKey'
      name: 'x-api-key'
      in: 'header'
  requestBodies:
    ComposeHtmlPayload:
      description: 'Request payload for composing content from HTML source'
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties: 
              html:
                type: string
              output:
                type: object
                properties:
                  type: 
                    type: string
                    enum:
                      - screenshot
                      - pdf
                  opts:
                    type: object
                    anyOf:
                      - $ref: '#/components/schemas/ScreenshotOptions'
                      - $ref: '#/components/schemas/PDFOptions'
                required:
                  - type
            required:
              - html
    ComposePdfPayload:
      description: 'Request payload for composing content from a PDF recipe'
      content:
        application/json:
          schema:
            type: object
            additionalProperties: false
            properties: 
              recipe:
                type: object
                properties:
                  layers:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                          format: uri
                          example: 'https://s3-eu-west-1.amazonaws.com/serverless-pdf-tools-api-dev/examples/KM_parhaat_pohja.pdf'
                      required:
                        - url
                  fonts:
                    type: array
                    items:
                      type: object
                      properties:
                        family:
                          type: string
                          example: arial
                        url:
                          type: string
                          format: uri
                          example: https://s3-eu-west-1.amazonaws.com/serverless-pdf-tools-api-dev/fonts/arial.ttf
                      required: 
                      - family
                      - url
                  fields:
                    type: array
                    items:
                      type: object
                      properties:
                        page:
                          anyOf:
                            - type: integer
                            - type: string
                              enum:
                                - all
                          example: 0
                        x:
                          type: number
                        y: 
                          type: number
                        text:
                          type: string
                        font:
                          type: string
                          example: arial
                        size:
                          type: number
                          example: 12
                        color:
                          type: string
                          example: 0,0,0,100
                        lineHeight:
                          type: number
                          example: 1
                        align: 
                          type: string
                          enum:
                            - left
                            - center
                            - right
                        rotation:
                          type: number
                      required:
                        - page
                        - x
                        - y
                        - text
                        - font
                        - size
                        - color
                required:
                  - layers
              output:
                type: object
                properties:
                  type: 
                    type: string
                    enum:
                      - pdf
                      - cover
                      - montage
                  opts:
                    type: object
                    additionalProperties: true
                required:
                  - type
  schemas: 
    ScreenshotOptions:
      type: object
      additionalProperties: true
      properties:
        path:
          type: string
        type:
          type: string
          enum:
            - jpeg
            - png
        quality:
          type: number
        fullPage:
          type: boolean
        clip:
          type: object
          properties:
            x:
              type: number
            y:
              type: number
            width:
              type: number
            height:
              type: number
        omitBackground:
          type: boolean
          default: false
    PDFOptions:
      type: object
      additionalProperties: true
      properties:
        path:
          type: string
        scale:
          type: number
          default: 1
        displayHeaderFooter:
          type: boolean
        headerTemplate: 
          type: string
        footerTemplate:
          type: string
        printBackground:
          type: boolean
          default: true
        landscape: 
          type: boolean
        pageRanges:
          type: string
        format: 
          type: string
          enum:
            - Letter
            - Legal
            - Tabload
            - Ledger
            - A0
            - A1
            - A2
            - A3
            - A4
            - A5
        width:
          type: string
          default: 100%
        height:
          type: string
          default: 100%
        margin: 
          type: object
          properties:
            top:
              type: string
            right:
              type: string
            bottom:
              type: string
            left:
              type: string
        preferCSSPageSize:
          type: boolean
        emulateMedia:
          type: string
          enum:
            - screen
            - print
