service: ${env:PROJECT_NAME}

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: dev
  environment:
    BASEURL: ${self:custom.env.${self:provider.stage}.BASEURL}
    BUCKET_NAME: ${self:custom.env.${self:provider.stage}.BUCKET_NAME}
  apiKeys:
    - ${self:service}-${self:provider.stage}-key
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::${self:custom.env.${self:provider.stage}.BUCKET_NAME}/*

functions:
  pdf:
    handler: dist/pdf.handler
  api:
    handler: dist/api.handler
    events:
      - http:
          path: /
          method: ANY
          private: true
          cors: true
          timeout: 60
      - http:
          path: /{path+}
          method: ANY
          private: true
          cors: true
          timeout: 60

plugins:
  - serverless-offline
  - serverless-stack-output

custom:
  serverless-offline:
    port: ${env:PORT}
    apiKey: ${env:API_KEY}
    dontPrintOutput: true
  apigwBinary:
    types: []
  output:
    handler: scripts/build-swaggerui.handler
  env:
    local:
      BUCKET_NAME: ${self:service}-dev
      BASEURL: http://localhost:${env:PORT}
    dev:
      BUCKET_NAME: ${self:service}-${self:provider.stage}
      BASEURL:
        Fn::Join: [
          "", [
            "https://",
            { "Ref" : "ApiGatewayRestApi" },
            ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}"
          ]
        ]

package:
  exclude:
    - './**' # exclude everything but dist and deps
    - '!node_modules/**' # can't use include or otherwise dev deps will be bundled
    - '!dist/**'
    - '!openapi.yml'

resources:
  Resources:
    APIBucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:provider.environment.BUCKET_NAME}
        WebsiteConfiguration:
          IndexDocument: index.html
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - HEAD
              MaxAge: 3000
    ApiBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: APIBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
              - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                    "arn:aws:s3:::",
                    {
                      "Ref": "APIBucket"
                    },
                    "/*"
                  ]
                ]
  Outputs:
    APIBucketName:
      Value:
        Ref: APIBucket

